In [2]:
import sqlite3
import pandas as pd
conn=sqlite3.connect('database.db')
cursor=conn.cursor()
#----create table------
cursor.execute(""" CREATE TABLE customers (cid INTEGER PRIMARY KEY ,order_name TEXT,amount INTEGER);""")
conn.commit()
data=pd.DataFrame({"cid":[1,2,3],"order_name":["egg","orange","apple"],"amount":[123,234,345]})
data.to_sql("customers", conn, if_exists="replace", index=False)
df=pd.read_sql('SELECT * FROM customers', conn)
print(df)

   cid order_name  amount
0    1        egg     123
1    2     orange     234
2    3      apple     345


In [22]:
import numpy as np
arr=np.array([1,2,3])
# print(arr)
# print(arr.shape)
# print(arr.ndim)
# print(arr.size)
# print(arr+1)
# print(arr*2)
# print(arr.mean())
# print(arr.sum())
# np.zeros((2,2))
# np.ones((2,2))
# np.arange(0,10)
# np.linspace(0,1,5)
print(arr.dtype)



int64


In [33]:
import numpy as np
arr = np.array([10, 20, 30,40])
arr1=np.array([1,2,3])
print(arr[0])
print(arr+5)
print(arr.max())
print(arr.min())
arr.reshape(2,2)
np.concatenate((arr1,arr))

10
[15 25 35 45]
40
10


array([ 1,  2,  3, 10, 20, 30, 40])

In [8]:
# slicing and indexing
import numpy as np
arr=np.array([1,2,3,5,6,7,8])
print(arr[1:5])

arr2 = np.array([[1, 2], [3, 4]])
print(arr2[0,1])

#silcing in 2D array
print(arr2[:,0])
print(arr2[:,1])
print(arr2[0,:])
print(arr2[1,:])
print(arr2[-1])






[2 3 5 6]
2
[1 3]
[2 4]
[1 2]
[3 4]
[3 4]


In [ ]:
# Reshaping and Manipulation in NumPy


